export const FETCH_CATEGORIES_START = 'FETCH_CATEGORIES_START';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAIL = 'FETCH_CATEGORIES_FAIL';
export const SELECT_CATEGORY = 'SELECT_CATEGORY';

export const FETCH_JOKES_START = 'FETCH_JOKES_START';
export const FETCH_JOKES_SUCCESS = 'FETCH_JOKES_SUCCESS';
export const FETCH_JOKES_FAIL = 'FETCH_JOKES_FAIL';

export const FETCH_FAVS_START = 'FETCH_FAVS_START';
export const FETCH_FAVS_SUCCESS = 'FETCH_FAVS_SUCCESS';
export const FETCH_FAVS_FAIL = 'FETCH_FAVS_FAIL';
export const ADD_TO_FAV_LIST = 'ADD_TO_FAV_LIST';
export const REMOVE_FROM_FAV_LIST = 'REMOVE_FROM_FAV_LIST';
